"""Backward-facing-step (BFS) validation cases: geometry, inlet profiles, analysis.

Geometry (x streamwise, y wall-normal, z spanwise; step at x = 0)::

        y = S+h  +-------------------------------------------------+ topWall
                 |  inlet channel |                                 |
   inlet --->    |   (length Lin) |                                 | outlet
        y = S    +----------------+                                 |
                  inletBottomWall |stepWall                         |
        y = 0                     +---------------------------------+ bottomWall
                 x = -Lin        x = 0                             x = Ld

2D cases are one cell thick (``frontAndBack`` empty). 3D cases model half the
span: ``midPlane`` (z = 0) is a symmetry plane and ``sideWall`` (z = W/2) is a
no-slip wall, which is what introduces the sidewall three-dimensionality that
Armaly et al. (1983) observed above Re ~ 400.
"""
from __future__ import annotations

import math
import shutil
from dataclasses import dataclass, asdict
from pathlib import Path

import numpy as np

from .case import AIR, TEMPLATES, _copy_render
from .foamio import Case, PolyMesh, final_residuals

NU_AIR = AIR["mu_air"] / AIR["rho_air"]


@dataclass
class BFSParams:
    Re: float                  # U_mean * 2h / nu   (Armaly et al. 1983 definition)
    S_mm: float = 4.9          # step height
    h_mm: float = 5.2          # inlet-channel height  (ER = (S+h)/h = 1.942)
    Lin_S: float = 5.0         # inlet-channel length / S (0 -> profile imposed at the step)
    Ld_S: float = 40.0         # downstream length / S
    n_S: int = 20              # cells per step height (y)
    aspect: float = 2.0        # dx / dy
    W_half_mm: float | None = None   # half-span for 3D (None -> 2D)
    nz: int = 30               # spanwise cells (3D)
    z_grading: float = 0.1     # last/first spanwise cell size (fine at the sidewall)
    nIter: int = 4000
    nProcs: int = 1

    @property
    def U_mean(self) -> float:
        return self.Re * NU_AIR / (2 * self.h_mm * 1e-3)

    @property
    def ER(self) -> float:
        return (self.S_mm + self.h_mm) / self.h_mm

    @property
    def is3d(self) -> bool:
        return self.W_half_mm is not None

    def counts(self):
        dy = self.S_mm / self.n_S
        dx = self.aspect * dy
        n = lambda L, d: max(1, int(round(L / d)))
        return dict(nyS=self.n_S, nyh=n(self.h_mm, dy),
                    nxd=n(self.Ld_S * self.S_mm, dx), nxi=n(self.Lin_S * self.S_mm, dx),
                    nz=self.nz if self.is3d else 1)

    def n_cells(self) -> int:
        c = self.counts()
        cells = c["nxd"] * (c["nyS"] + c["nyh"])
        if self.Lin_S > 0:
            cells += c["nxi"] * c["nyh"]
        return cells * c["nz"]


# --------------------------------------------------------------------------- #
def block_mesh_dict(p: BFSParams) -> str:
    S, h = p.S_mm, p.h_mm
    Ld, Lin = p.Ld_S * S, p.Lin_S * S
    Z = p.W_half_mm if p.is3d else S / p.n_S
    c = p.counts()
    gz = p.z_grading if p.is3d else 1.0
    V = [(0, 0), (Ld, 0), (Ld, S), (0, S), (Ld, S + h), (0, S + h), (-Lin, S), (-Lin, S + h)]
    verts = [(x, y, 0.0) for x, y in V] + [(x, y, Z) for x, y in V]
    vtxt = "\n".join(f"    ({x:.6g} {y:.6g} {z:.6g})  // {i}" for i, (x, y, z) in enumerate(verts))
    blocks = [
        f"    hex (0 1 2 3 8 9 10 11)   ({c['nxd']} {c['nyS']} {c['nz']}) simpleGrading (1 1 {gz})",
        f"    hex (3 2 4 5 11 10 12 13) ({c['nxd']} {c['nyh']} {c['nz']}) simpleGrading (1 1 {gz})",
    ]
    inlet = "(6 14 15 7)" if Lin > 0 else "(3 11 13 5)"
    top = "(5 4 12 13)" + (" (7 5 13 15)" if Lin > 0 else "")
    z0 = ["(0 3 2 1)", "(3 5 4 2)"] + (["(6 7 5 3)"] if Lin > 0 else [])
    z1 = ["(8 9 10 11)", "(11 10 12 13)"] + (["(14 11 13 15)"] if Lin > 0 else [])
    if Lin > 0:
        blocks.append(f"    hex (6 3 5 7 14 11 13 15) ({c['nxi']} {c['nyh']} {c['nz']}) simpleGrading (1 1 {gz})")
    extra = f"    inletBottomWall {{ type wall; faces ((6 3 11 14)); }}\n" if Lin > 0 else ""
    if p.is3d:
        zp = (f"    midPlane {{ type symmetryPlane; faces ({' '.join(z0)}); }}\n"
              f"    sideWall {{ type wall; faces ({' '.join(z1)}); }}\n")
    else:
        zp = f"    frontAndBack {{ type empty; faces ({' '.join(z0 + z1)}); }}\n"
    return f"""FoamFile {{ version 2.0; format ascii; class dictionary; object blockMeshDict; }}
// Backward-facing step, generated by coolchan/bfs.py
// S = {S} mm, h = {h} mm, ER = {p.ER:.3f}, Re(U_mean 2h/nu) = {p.Re:g}, {'3D half-span' if p.is3d else '2D'}

convertToMeters 0.001;

vertices
(
{vtxt}
);

blocks
(
{chr(10).join(blocks)}
);

boundary
(
    inlet      {{ type patch; faces ({inlet}); }}
    outlet     {{ type patch; faces ((1 2 10 9) (2 4 12 10)); }}
    bottomWall {{ type wall;  faces ((0 1 9 8)); }}
    stepWall   {{ type wall;  faces ((0 8 11 3)); }}
    topWall    {{ type wall;  faces ({top}); }}
{extra}{zp});
"""


def build_bfs(case_dir: Path, p: BFSParams) -> Path:
    case_dir = Path(case_dir)
    if case_dir.exists():
        shutil.rmtree(case_dir)
    toks = dict(nu=NU_AIR, nIter=p.nIter, writeInterval=max(1, p.nIter // 10),
                nProcs=p.nProcs)
    _copy_render(TEMPLATES / "bfs", case_dir, toks)
    (case_dir / "system" / "blockMeshDict").write_text(block_mesh_dict(p))
    (case_dir / "params.json").write_text(__import__("json").dumps(asdict(p)))
    return case_dir


# --------------------------------------------------------------------------- #
def duct_profile(y, z, a, b, n_terms=41):
    """Fully developed laminar u(y, z) in a rectangular duct |y|<=a, |z|<=b (unscaled).

    White, Viscous Fluid Flow, eq. 3-48 (series in odd i).
    """
    u = np.zeros_like(y, dtype=float)
    for i in range(1, 2 * n_terms, 2):
        k = i * math.pi / (2 * a)
        # cosh ratio written with exponentials to avoid overflow for wide ducts
        ratio = np.exp(k * (np.abs(z) - b)) * (1 + np.exp(-2 * k * np.abs(z))) / (1 + math.exp(-2 * k * b))
        u += (-1) ** ((i - 1) // 2) * (1 - ratio) * np.cos(k * y) / i**3
    return u


def write_inlet_velocity(case_dir: Path, p: BFSParams):
    """Write 0/air/U with the exact fully developed profile on the inlet faces."""
    case_dir = Path(case_dir)
    m = PolyMesh(case_dir / "constant" / "polyMesh")
    Cf = m.patch_centres("inlet") * 1e3           # mm
    A = np.linalg.norm(m.patch_areas("inlet"), axis=1)
    yc = Cf[:, 1] - (p.S_mm + p.h_mm / 2)         # centred in the inlet channel
    if p.is3d:
        u = duct_profile(yc, Cf[:, 2], p.h_mm / 2, p.W_half_mm)
    else:
        eta = (Cf[:, 1] - p.S_mm) / p.h_mm
        u = eta * (1 - eta)
    if p.is3d:
        # Armaly et al. define Re with V = 2/3 of the measured centre-line maximum, so
        # match that (the duct bulk velocity is ~1.8 % lower for aspect ratio 36)
        u *= 1.5 * p.U_mean / u.max()
    else:
        u *= p.U_mean / ((u * A).sum() / A.sum())   # exact bulk velocity -> exact Re
    vals = "\n".join(f"({v:.8g} 0 0)" for v in u)
    Ui = p.U_mean * p.h_mm / (p.S_mm + p.h_mm)
    txt = f"""FoamFile {{ version 2.0; format ascii; class volVectorField; location "0"; object U; }}
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform ({Ui:.6g} 0 0);

boundaryField
{{
    inlet
    {{
        type            fixedValue;     // fully developed profile, U_mean = {p.U_mean:.6g} m/s
        value           nonuniform List<vector> {len(u)}
(
{vals}
);
    }}
    outlet          {{ type inletOutlet; inletValue uniform (0 0 0); value $internalField; }}
    ".*Wall"        {{ type noSlip; }}
    midPlane        {{ type symmetryPlane; }}
    frontAndBack    {{ type empty; }}
}}
"""
    d = case_dir / "0"
    if d.exists():
        shutil.rmtree(d)
    shutil.copytree(case_dir / "0.orig", d)
    (d / "U").write_text(txt)


# --------------------------------------------------------------------------- #
def _crossings(x, u):
    """x positions where u changes sign, with direction (+1: - to +, -1: + to -)."""
    s = np.sign(u)
    out = []
    for i in np.where(s[:-1] * s[1:] < 0)[0]:
        xc = x[i] - u[i] * (x[i + 1] - x[i]) / (u[i + 1] - u[i])
        out.append((xc, 1 if u[i] < 0 else -1))
    return out


def reattachment(case_dir, p: BFSParams, time=None) -> dict:
    """Separation/reattachment lengths in step heights, on the mid-span plane.

    x1: lower-wall reattachment; x4, x5: upper-wall separation and reattachment
    (Armaly et al. notation). Uses the sign of u in the wall-adjacent cells.
    """
    c = Case(case_dir)
    m = c.mesh("")
    U = c.field("U", "", time).internal[:, 0]
    S = p.S_mm * 1e-3
    res = {}
    for patch, key in (("bottomWall", "lower"), ("topWall", "upper")):
        cells = m.patch_cells(patch)
        xc = m.C[cells, 0]
        if p.is3d:
            zc = m.C[cells, 2]
            sel = np.isclose(zc, zc.min())            # row nearest the symmetry plane
            cells, xc = cells[sel], xc[sel]
        keep = xc > 0
        o = np.argsort(xc[keep])
        res[key] = _crossings(xc[keep][o] / S, U[cells[keep][o]])
    lower = res["lower"]
    x1 = max((x for x, d in lower if d == 1), default=np.nan)
    upper = res["upper"]
    x4 = next((x for x, d in upper if d == -1), np.nan)
    x5 = next((x for x, d in upper if d == 1 and x > x4), np.nan)
    out = dict(x1=float(x1), x4=float(x4), x5=float(x5))
    log = Path(case_dir) / "log.simpleFoam"
    if log.exists():
        r = final_residuals(log)
        out["max_residual"] = max(r.values()) if r else np.nan
    return out


def reattachment_span(case_dir, p: BFSParams, time=None):
    """Lower-wall reattachment x1/S for every spanwise row of cells (3D cases)."""
    c = Case(case_dir)
    m = c.mesh("")
    U = c.field("U", "", time).internal[:, 0]
    S = p.S_mm * 1e-3
    cells = m.patch_cells("bottomWall")
    x, z = m.C[cells, 0], np.round(m.C[cells, 2], 9)
    zs = np.unique(z)
    x1 = []
    for zz in zs:
        sel = (z == zz) & (x > 0)
        o = np.argsort(x[sel])
        cr = _crossings(x[sel][o] / S, U[cells[sel]][o])
        x1.append(max((a for a, d in cr if d == 1), default=np.nan))
    return zs / S, np.array(x1)


def reattachment_iter_change(case_dir, p: BFSParams) -> float:
    t = Case(case_dir).times()
    if len(t) < 3:
        return float("nan")
    a = reattachment(case_dir, p, t[-1])["x1"]
    b = reattachment(case_dir, p, t[-2])["x1"]
    return abs(a - b)
