"""Tensor-product ("lattice") multi-block meshes for layered, box-shaped assemblies.

The domain is cut by planes x = xs[i], y = ys[j], z = zs[k] into a lattice of
boxes. Each box is either assigned to a cell zone (a material/region) or left
empty (void). ``blockMesh`` meshes the boxes; ``splitMeshRegions -cellZones``
then turns zones into regions and creates the ``A_to_B`` coupling patches.
Faces on the outside of the assembly are classified into named patches by a
user callback, so every external boundary condition has an explicit home.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional

# local vertex numbers of each block face, outward normal
FACES = {
    "-x": (0, 4, 7, 3), "+x": (1, 2, 6, 5),
    "-y": (0, 1, 5, 4), "+y": (3, 7, 6, 2),
    "-z": (0, 3, 2, 1), "+z": (4, 5, 6, 7),
}
STEP = {"-x": (-1, 0, 0), "+x": (1, 0, 0), "-y": (0, -1, 0), "+y": (0, 1, 0),
        "-z": (0, 0, -1), "+z": (0, 0, 1)}


@dataclass
class Axis:
    lines: list            # breakpoints (mm)
    cells: list            # cells per band
    grading: list = None   # simpleGrading ratio per band (last/first)

    def __post_init__(self):
        assert len(self.cells) == len(self.lines) - 1
        if self.grading is None:
            self.grading = [1.0] * len(self.cells)

    @property
    def n(self):
        return len(self.cells)

    def band(self, lo, hi):
        """Indices of bands inside [lo, hi]."""
        return [i for i in range(self.n) if self.lines[i] >= lo - 1e-9 and self.lines[i + 1] <= hi + 1e-9]


@dataclass
class Lattice:
    x: Axis
    y: Axis
    z: Axis
    zone: Callable[[int, int, int], Optional[str]]
    classify: Callable[[int, int, int, str], tuple]     # -> (patch name, patch type)
    patches: dict = field(default_factory=dict)

    def _vid(self, i, j, k):
        return (k * (self.y.n + 1) + j) * (self.x.n + 1) + i

    def block_mesh_dict(self, title="") -> str:
        X, Y, Z = self.x, self.y, self.z
        verts = []
        for k in range(Z.n + 1):
            for j in range(Y.n + 1):
                for i in range(X.n + 1):
                    verts.append(f"    ({X.lines[i]:.6g} {Y.lines[j]:.6g} {Z.lines[k]:.6g})")
        blocks, faces = [], {}
        for k in range(Z.n):
            for j in range(Y.n):
                for i in range(X.n):
                    zn = self.zone(i, j, k)
                    if zn is None:
                        continue
                    v = [self._vid(i, j, k), self._vid(i + 1, j, k), self._vid(i + 1, j + 1, k),
                         self._vid(i, j + 1, k), self._vid(i, j, k + 1), self._vid(i + 1, j, k + 1),
                         self._vid(i + 1, j + 1, k + 1), self._vid(i, j + 1, k + 1)]
                    blocks.append(
                        f"    hex ({' '.join(map(str, v))}) {zn} ({X.cells[i]} {Y.cells[j]} {Z.cells[k]}) "
                        f"simpleGrading ({X.grading[i]:g} {Y.grading[j]:g} {Z.grading[k]:g})")
                    for d, fv in FACES.items():
                        di, dj, dk = STEP[d]
                        ii, jj, kk = i + di, j + dj, k + dk
                        inside = 0 <= ii < X.n and 0 <= jj < Y.n and 0 <= kk < Z.n
                        if inside and self.zone(ii, jj, kk) is not None:
                            continue                      # internal (same or other zone)
                        name, ptype = self.classify(i, j, k, d)
                        self.patches[name] = ptype
                        faces.setdefault(name, []).append("(" + " ".join(str(v[q]) for q in fv) + ")")
        bnd = []
        for name, fl in faces.items():
            body = "\n".join("            " + f for f in fl)
            bnd.append(f"    {name}\n    {{\n        type {self.patches[name]};\n        faces\n        (\n{body}\n        );\n    }}")
        return f"""FoamFile {{ version 2.0; format ascii; class dictionary; object blockMeshDict; }}
// {title}
// Generated by coolchan/lattice.py - {len(blocks)} blocks

convertToMeters 0.001;

vertices
(
{chr(10).join(verts)}
);

blocks
(
{chr(10).join(blocks)}
);

boundary
(
{chr(10).join(bnd)}
);
"""

    def n_cells(self) -> int:
        n = 0
        for k in range(self.z.n):
            for j in range(self.y.n):
                for i in range(self.x.n):
                    if self.zone(i, j, k) is not None:
                        n += self.x.cells[i] * self.y.cells[j] * self.z.cells[k]
        return n
